services:

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID={PUID}
      - PGID={PGID}
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - /media/big_boi/Books/Books:/books
      - /media/big_boi/Books/Comics:/comics
    ports:
      - 5000:5000
    restart: unless-stopped
    #networks:
    #  - swag_proxy
    #labels:
    #  - "com.centurylinklabs.watchtower.enable=true"

#networks:
#  swag_proxy:
#    external: true
