version: "3.7"
services:
  eufy-ws:
    image: bropat/eufy-security-ws
    container_name: eufy-ws
    network_mode: "bridge"
    volumes:
        - ./data:/data
    ports:
      - "3000:3000"
    env_file:
      - ./.env
